@startuml
User->Csv.vue:Enter the CSV view
activate Csv.vue

Csv.vue->VuexState:GetVessels
activate VuexState
return Return Vessels
return Show Vessels in Dropdown Menu

User->Csv.vue:Specify Ship from Dropdown Menu
Csv.vue->VuexState:GetLogVar
activate VuexState
return Return LogVar

User<--Csv.vue:Show LogVar for ship
User->Csv.vue:Specify LogVar+Time+Granularity

Csv.vue->KymaDataCenter:Get Batch of Data as CSV
activate KymaDataCenter
Csv.vue<--KymaDataCenter:Return CSV Data
deactivate KymaDataCenter

Csv.vue->mainThread:Event: Create CSV File
activate mainThread
mainThread<-mainThread:write file
return Event: File Write Complete

User<--Csv.vue:Feedback: CSV file created

deactivate Csv.vue
@enduml