@startuml
User->Login.vue:Input(e-mail,password)
activate Login.vue

Login.vue->Login.vue:Validate Input

alt Successful Validation
Login.vue->AuthenticationUtil.js
activate AuthenticationUtil.js

 AuthenticationUtil.js->KymaDataCenter:Authenticate Login
 activate KymaDataCenter
 alt Successful Authentication

  KymaDataCenter-->AuthenticationUtil.js: 200 OK
  AuthenticationUtil.js-->Login.vue:Boolean: Authenticated
  Login.vue-->User:Route to Home Dashboard
 else Authentication Failure

  KymaDataCenter-->AuthenticationUtil.js: 401 Authentication Error
  deactivate KymaDataCenter
  AuthenticationUtil.js-->Login.vue:Boolean: Authenticated
  Login.vue-->User:Display Error Message
  end

else Validation Failure

 AuthenticationUtil.js-->Login.vue: Return: Error Message
 deactivate AuthenticationUtil.js
 Login.vue-->User:Display Error Message
 deactivate Login.vue
 end
@enduml
