*Router navigation:
@startuml
User->Router:Start App
activate Router

User<--Router:Route to Login.vue
User->Login.vue:Input Username & Password
activate Login.vue

Router<--Login.vue:Successful Login
deactivate Login.vue
User<--Router:Route to Vessels.vue

User->Vessels.vue:Click on Vessel
activate Vessels.vue

Router<--Vessels.vue:Return vessel ID
deactivate Vessels.vue

User<--Router:Route to /vessels/ID

User->vessel.vue:Look at Graphs
activate vessel.vue
vessel.vue<-vessel.vue:Create Graphs
User<--vessel.vue:Show Graphs
deactivate vessel.vue


deactivate Router
@enduml
